import {
  resolveDeliveryFromEmail,
  sendDeliveryEmail,
} from "@/lib/delivery/email/client";
import type {
  DeliveryProcessedListing,
  DeliveryTenant,
} from "@/lib/delivery/types";

function formatRunDate(date = new Date()) {
  return new Intl.DateTimeFormat("en-AU", {
    day: "numeric",
    month: "short",
    year: "numeric",
    timeZone: "Australia/Brisbane",
  }).format(date);
}

function reportLinksHtml(item: DeliveryProcessedListing) {
  const parts: string[] = [];

  if (item.reports.str) {
    parts.push(
      `<li><strong>STR report</strong> — <a href="${item.reports.str.publicUrl}">View online</a> · <a href="${item.reports.str.pdfUrl}">Download PDF</a></li>`,
    );
  }

  if (item.reports.lease) {
    parts.push(
      `<li><strong>Lease appraisal</strong> — <a href="${item.reports.lease.publicUrl}">View online</a> · <a href="${item.reports.lease.pdfUrl}">Download PDF</a></li>`,
    );
  }

  return parts.join("\n");
}

function reportLinksText(item: DeliveryProcessedListing) {
  const lines: string[] = [];

  if (item.reports.str) {
    lines.push(`STR report: ${item.reports.str.publicUrl}`);
    lines.push(`STR PDF: ${item.reports.str.pdfUrl}`);
  }

  if (item.reports.lease) {
    lines.push(`Lease appraisal: ${item.reports.lease.publicUrl}`);
    lines.push(`Lease PDF: ${item.reports.lease.pdfUrl}`);
  }

  return lines.join("\n");
}

function buildDigestSubject(tenant: DeliveryTenant, count: number) {
  const name = tenant.brand?.displayName?.trim() || tenant.name;
  return `${name} reports — ${count} new propert${count === 1 ? "y" : "ies"} (${formatRunDate()})`;
}

function buildDigestHtml(tenant: DeliveryTenant, items: DeliveryProcessedListing[]) {
  const name = tenant.brand?.displayName?.trim() || tenant.name;
  const blocks = items
    .map(
      (item) => `
<section style="margin-bottom:24px;">
  <h3 style="margin:0 0 8px;font-size:16px;">${item.address}</h3>
  <p style="margin:0 0 8px;color:#555;font-size:13px;"><a href="${item.listingUrl}">Listing source</a></p>
  <ul style="margin:0;padding-left:20px;">${reportLinksHtml(item)}</ul>
</section>`,
    )
    .join("\n");

  return `<!DOCTYPE html>
<html>
<body style="font-family:Inter,Arial,sans-serif;color:#111;line-height:1.5;">
  <p>Hi,</p>
  <p>Your latest ${name} property reports are ready:</p>
  ${blocks}
  <p style="color:#666;font-size:13px;">Generated by StayPacks delivery.</p>
</body>
</html>`;
}

function buildDigestText(tenant: DeliveryTenant, items: DeliveryProcessedListing[]) {
  const name = tenant.brand?.displayName?.trim() || tenant.name;
  const blocks = items
    .map(
      (item) =>
        `${item.address}\nListing: ${item.listingUrl}\n${reportLinksText(item)}`,
    )
    .join("\n\n");

  return `Your latest ${name} property reports are ready:\n\n${blocks}`;
}

export async function sendDeliveryDigestEmail({
  tenant,
  items,
}: {
  tenant: DeliveryTenant;
  items: DeliveryProcessedListing[];
}) {
  if (!items.length) {
    return null;
  }

  const subject = buildDigestSubject(tenant, items.length);
  const text = buildDigestText(tenant, items);
  const html = buildDigestHtml(tenant, items);

  return sendDeliveryEmail({
    from: resolveDeliveryFromEmail(tenant.email_from),
    to: tenant.email_recipients,
    subject,
    text,
    html,
  });
}

export function logDeliveryDigestPreview(
  tenant: DeliveryTenant,
  items: DeliveryProcessedListing[],
) {
  console.info("[delivery] digest preview (shadow mode)", {
    tenant: tenant.slug,
    to: tenant.email_recipients,
    subject: buildDigestSubject(tenant, items.length),
    items: items.map((item) => ({
      address: item.address,
      listingUrl: item.listingUrl,
      str: item.reports.str?.publicUrl,
      lease: item.reports.lease?.publicUrl,
    })),
  });
}
