export const CLASSIC_SALES_APPRAISAL_TEMPLATE_ID = "classic-sales-appraisal";
export const BOLD_SALES_APPRAISAL_TEMPLATE_ID = "bold-sales-appraisal";
export const GALLERY_SALES_APPRAISAL_TEMPLATE_ID = "gallery-sales-appraisal";
export const EDITORIAL_SALES_APPRAISAL_TEMPLATE_ID = "editorial-sales-appraisal";
export const SPLIT_SALES_APPRAISAL_TEMPLATE_ID = "split-sales-appraisal";
export const REFINED_SALES_APPRAISAL_TEMPLATE_ID = "refined-sales-appraisal";
export const MINIMALIST_SALES_APPRAISAL_TEMPLATE_ID = "minimalist-sales-appraisal";
export const LANDMARK_SALES_APPRAISAL_TEMPLATE_ID = "landmark-sales-appraisal";

export const SALES_APPRAISAL_TEMPLATE_IDS = [
  CLASSIC_SALES_APPRAISAL_TEMPLATE_ID,
  BOLD_SALES_APPRAISAL_TEMPLATE_ID,
  GALLERY_SALES_APPRAISAL_TEMPLATE_ID,
  EDITORIAL_SALES_APPRAISAL_TEMPLATE_ID,
  SPLIT_SALES_APPRAISAL_TEMPLATE_ID,
  REFINED_SALES_APPRAISAL_TEMPLATE_ID,
  MINIMALIST_SALES_APPRAISAL_TEMPLATE_ID,
  LANDMARK_SALES_APPRAISAL_TEMPLATE_ID,
] as const;

export const DEFAULT_SALES_APPRAISAL_TEMPLATE_ID = CLASSIC_SALES_APPRAISAL_TEMPLATE_ID;
